spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/hichat?createDatabaseIfNotExist=true
    username: root
    password:
  devtools:
    restart:
      enabled: true

  data:
    jpa:
      repositories:
        base-package: org.example.repository